on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
      - 'phpstan.neon'
  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
      - 'phpstan.neon'

name: backwards compatibility

jobs:
  roave_bc_check:
    uses: yiisoft/actions/.github/workflows/bc.yml@dev-master
    with:
      usePackageBin: true
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
