name: static analysis with PHPStan

on:
  pull_request:
    paths: &paths
      - 'composer.json'
      - 'config/**'
      - 'phpstan.neon'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/phpstan.yml'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    uses: yiisoft/actions/.github/workflows/phpstan.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2', '8.3', '8.4', '8.5']
